=== XiaoyanYangAlice/XML-Annotation/gardens.dtd
<!-- part1 teiHeading -->
<!ELEMENT TEI (teiHeader,text)>
    <!ELEMENT teiHeader (fileDesc)>
        <!ELEMENT fileDesc (titleStmt,sourceDesc)>
            <!ELEMENT titleStmt (title, author)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT author (#PCDATA)>
            <!ELEMENT sourceDesc (#PCDATA)>

<!-- part2 teiText -->
    <!ELEMENT text (div+)>
        <!ELEMENT div (head,body,address)>
        <!ATTLIST div  type CDATA #REQUIRED>
        <!ATTLIST div  n CDATA #REQUIRED>

            <!ELEMENT head (#PCDATA)>

            <!ELEMENT body (p+)>
                <!ELEMENT p (#PCDATA | persName | placeName | emph | measure | num | date | term | orgName)*>
                <!ATTLIST p type CDATA #REQUIRED>
                    <!ELEMENT persName (#PCDATA)>
                    <!ATTLIST persName type CDATA #REQUIRED>

                    <!ELEMENT placeName (#PCDATA | geogName)*>
                    <!ATTLIST placeName type CDATA #IMPLIED>
                        <!ELEMENT  geogName  (#PCDATA)>
                        <!ATTLIST geogName type CDATA #REQUIRED>
                        
                    <!ELEMENT emph (#PCDATA)>
                    <!ATTLIST emph type CDATA #REQUIRED>
                    
                    <!ELEMENT measure (#PCDATA)>
                    <!ATTLIST measure type CDATA #REQUIRED>
                    
                    <!ELEMENT num (#PCDATA)>
                    <!ATTLIST num type CDATA #REQUIRED>
                    <!ATTLIST num value CDATA #REQUIRED>
                    
                    <!ELEMENT date (#PCDATA)>
                    <!ATTLIST date when CDATA #REQUIRED>
                    
                    <!ELEMENT term (#PCDATA)>
                    <!ATTLIST term type CDATA #REQUIRED>
                    
                    <!ELEMENT orgName (#PCDATA)>
                    <!ATTLIST orgName type CDATA #IMPLIED>



            <!ELEMENT address (street*, name*, city*, region, postCode)>
                <!ELEMENT street (#PCDATA)>
                <!ELEMENT name (#PCDATA)>
                <!ELEMENT city (#PCDATA)>
                <!ELEMENT region (#PCDATA)>
                <!ELEMENT postCode (#PCDATA)>

=== XiaoyanYangAlice/XML-Annotation/gardens.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE TEI SYSTEM 'gardens.dtd'>
<TEI>
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>10 London gardens with their history and design style</title>
                <author>Gardenvisit</author>
            </titleStmt>

            <sourceDesc>https://www.gardenvisit.com/gardens</sourceDesc>
        </fileDesc>

    </teiHeader>

    <text>
        <div n="1" type="Kensington Gardens (Park)">
            <head>Kensington Gardens (Park)</head>
            <body>
                <p type="history">
                    The greenspace called 'Kensington Gardens' was the deer park acquired by 
                    <persName type="King">Henry VIII</persName>.
                    It belonged to <placeName type="palace">Kensington palace</placeName> - and there is a good case for 
                    calling it '<placeName type="garden">Kensington Park'</placeName>. 
                    <persName type="royalMale">William III</persName> bought 
                    <term type="architecture">Nottingham House</term> for 
                    <num type="price" value="2000">£20,000</num> and converted it into 
                    <placeName type="palace">Kensington Palace</placeName>. 
                    <placeName>Kensington Park</placeName>' was made on land taken from 
                    <placeName type="park">Hyde Park</placeName> by <persName type="royalFemale">Queen Caroline</persName> 
                    (Caroline of Brandenburg-Ansbach, the wife of <persName type="royalMale">King George II</persName>). 
                    She employed <persName type="designer">Charles Bridgeman</persName> from <date when="1728-1738">1728-1738</date> 
                    to make a <emph type="gardenStyle">Baroque Style</emph> park, including 
                    the <placeName type="inside"><geogName type="avenues">avenues</geogName></placeName> 
                    and the <placeName type="inside"><geogName type="pond">Round Pond</geogName></placeName>. 
                    
                </p>
        
                <p type="design">
                    There was a <term type="architecture">bastioned wall</term> 
                    on <measure type="east">the east of boundary</measure> of '<placeName type="garden">Kensington Park</placeName>', 
                    on the line of what is now <placeName type="inside">the West Carriage Drive</placeName>, 
                    as shown on <persName type="designer">John Rocque</persName>'s <date when="1756">1756</date> plan.
                    Like a Ha-Ha in a landscape garden, the aim was to give a view of the surrounding countryside 
                    (in this case, <placeName type="park">Hyde Park</placeName>).
                    <persName type="designer">Charles Bridgeman</persName> is regarded as a 'transitional' designer and his biographer, 
                    <persName type="biographer">Peter Willis</persName>, saw him as a key figure in genesis of the landscape garden. 
                    If this is correct, then one can find evidence of 'the great revolution in taste' within 
                    the perimeter of <placeName type="garden">Kensington Gardens</placeName> and <placeName type="park">Hyde Park</placeName>.
                
                </p>
        
                <p type="scenery">
                    <measure type="west">The western part</measure> of <placeName type="garden">Kensington Gardens</placeName>, 
                    around <placeName type="palace">the Palace</placeName>, was definitely <emph type="gardenStyle">baroque</emph>.
                    The eastern section, where <placeName type="inside"><geogName type="avenues">the avenues</geogName></placeName> 
                    approach <placeName type="inside"><geogName type="lake">the Long Water</geogName></placeName>, is an 
                    early example of what became <emph type="gardenStyle">the Serpentine Style</emph>. 
                    <placeName type="park">Hyde Park</placeName>, with its 
                    <placeName><geogName type="lake">Serpentine lake</geogName></placeName>, 
                    was an early project in what was to become '<emph type="gardenStyle">the style of William Kent and Lancelot Brown</emph>'. 
                    The best point to see the transition is <term type="architecture">the Queen's Temple</term>, 
                    shown by the red marker baloon on the map below.
                    It was built as a feature in a bosquet and now has the appearance of a Temple in a landscape garden.
                </p>
        
                
        
                <p type="openness">
                    Kensington Gardens <emph type="openStatus">private</emph> for most of <date when="1700-1800">the eighteenth century</date> 
                    and then <emph type="openStatus">progressively opened to public access</emph>. 
                    <persName type="royalFemale">Queen Victoria</persName> granted <emph type="openStatus">full public access</emph> in 
                    <date when="1841">1841</date> but, probably because of their location, they have an upper-class air.
                </p>
            </body>

            
            <address>
                <street>Park Lane</street>
                <name>The Old Police House,Hyde Park</name>
                <city>London</city>
                <region>Greater London, England</region>
                <postCode>W2 2UH</postCode>
            </address>

        </div>    

        <div n="2" type="Barbican">

            <head>Barbican</head>
            <body>
                <p type="scenery">
                    A vast development in the City of London.
                    To some, it is a forest of tower blocks.
                    For others, there are many exciting features including 
                    <term type="architecture"> type="fountains,cascade,roof garden,trees,pools,sitting area">massed fountains, 
                    a cascade, roof gardens, trees growing on columns, great pools and 
                    a sitting area</term> which is set below water level.
                    It is a prime example of <emph type="gardenStyle">the Abstract Modern design style</emph>.
                    However, many of the spaces are bleak and draughty. 
                    Extensive pedestrian decks cover the parking areas and access roads. 
                </p>
        
                <p type="design">
                    The scheme was designed by <persName type="designer">Chamberlain Powell</persName> 
                    and <persName type="designer">Bon</persName> 
                    in the <date when="1950s">1950s</date> and is now almost complete.
                    Visitors joke that it is almost impossible to find one's way about. 
                    This has been countered by painting lines on the brick paviors.
                    One can follow them, as Theseus followed his string to escape from the Labyrinth.
                        
                </p>
        
                <p type="planting">
                    
                    The original planting of the roof gardens included <term type="plants">lawns, flower beds, 
                    trees and shrubs</term>, which required continual irrigation and a high maintenance regime.
                    
                    In <date when="2013">2013</date> the planting was revised by <persName type="designer">Nigel Dunnett</persName> to 
                    create three â€˜Designed Plant Communitiesâ€™ relating to the amout of sunshine the areas receive:
                        
                    1. <term type="plants">STEPPE plantings</term> in full sun.
                    Mixtures of <term type="plants">grasses and perennials</term> that are naturally adapted to dry, 
                    exposed conditions.
                    This is the main planting type across the site.
                    Very colourful, with jewel-like colours, diverse foliage textures and plant forms.

                    2. <term type="plants">SHRUB STEPPE plantings</term> which combine similar mixes of perennials and 
                    grasses to the steppe plantings, 
                    but with additional low-density shrubs and multi-stemmed trees, to create multi-layered plantings 
                    with year-round structure and interest.
                        
                    3. <term type="plants">LIGHT WOODLAND plantings</term> in part-shade, and where the growing medium 
                    depths enable tree growth.
                    Multi-stem trees, widely spaced create a light, open canopy, with a scattered understory of shrubs, 
                    and a diverse perennial ground layer.
                        
        
                </p>
    

            </body>


            <address>
                <street>Silk Street</street>
                <name>London Wall</name>
                <city>London</city>
                <region>Greater London, England</region>
                <postCode>EC2Y 8DS</postCode>
            </address>


        </div>

        <div n="3" type="Battersea Park">
            <head>Battersea Park</head>
            <body>
                <p type="history">
                    One of London's great <date when="1800s">nineteenth century</date> public parks. 
                    It was laid out between <date when="1846-1864">1846 and 1864</date> to designs by 
                    <persName type="designer">James Pennethorne</persName> and <persName type="designer">John Gibson</persName>.
                    The site, which was originally flat and swampy,
